### ISSUE TITLE
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader

### ISSUE THREAD

**Issue by disymayufei** [SerendipityR-2022/EndMinecraftPlusV2#15]
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at cn.serendipityr.EndMinecraftPlusV2.Tools.OtherUtils.loadLibrary(OtherUtils.java:83)
        at cn.serendipityr.EndMinecraftPlusV2.VersionControl.ProtocolLibs.scanProtocolLibs(ProtocolLibs.java:56)
        at cn.serendipityr.EndMinecraftPlusV2.VersionControl.ProtocolLibs.loadProtocolLib(ProtocolLibs.java:24)
        at cn.serendipityr.EndMinecraftPlusV2.EndMinecraftPlusV2.startAttack(EndMinecraftPlusV2.java:47)
        at cn.serendipityr.EndMinecraftPlusV2.EndMinecraftPlusV2.main(EndMinecraftPlusV2.java:29)

**Comment by SerendipityR-2022** [comment]
问题重复 #2
