### ISSUE TITLE
选择代理和选择Minecraft版本后报错

### ISSUE THREAD

**Issue by Whirity404** [SerendipityR-2022/EndMinecraftPlusV2#32]
内容：
```
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at cn.serendipityr.EndMinecraftPlusV2.Tools.OtherUtils.loadLibrary(OtherUtils.java:83)
        at cn.serendipityr.EndMinecraftPlusV2.VersionControl.ProtocolLibs.choseProtocolVer(ProtocolLibs.java:118)
        at cn.serendipityr.EndMinecraftPlusV2.VersionControl.ProtocolLibs.loadProtocolLib(ProtocolLibs.java:24)
        at cn.serendipityr.EndMinecraftPlusV2.EndMinecraftPlusV2.startAttack(EndMinecraftPlusV2.java:47)
        at cn.serendipityr.EndMinecraftPlusV2.EndMinecraftPlusV2.main(EndMinecraftPlusV2.java:29)
Exception in thread "main" java.lang.NoClassDefFoundError: com/github/steveice10/packetlib/packet/Packet
        at cn.serendipityr.EndMinecraftPlusV2.VersionControl.ProtocolLibs.loadProtocolLib(ProtocolLibs.java:29)
        at cn.serendipityr.EndMinecraftPlusV2.EndMinecraftPlusV2.startAttack(EndMinecraftPlusV2.java:47)
        at cn.serendipityr.EndMinecraftPlusV2.EndMinecraftPlusV2.main(EndMinecraftPlusV2.java:29)
Caused by: java.lang.ClassNotFoundException: com.github.steveice10.packetlib.packet.Packet
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 3 more
```

**Comment by SerendipityR-2022** [comment]
见“常见问题”部分，切换到jdk1.8环境即可
