### ISSUE TITLE
在Linux服务器上运行时报错

### ISSUE THREAD

**Issue by Bliod-Cook** [SerendipityR-2022/EndMinecraftPlusV2#9]
显示
`Exception in thread "main" java.lang.UnsatisfiedLinkError: Error looking up function 'SetConsoleTitleA': java: undefined symbol: SetConsoleTitleA
        at com.sun.jna.Function.<init>(Function.java:252)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:604)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:580)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:566)
        at com.sun.jna.Library$Handler.invoke(Library.java:243)
        at com.sun.proxy.$Proxy0.SetConsoleTitleA(Unknown Source)
        at cn.serendipityr.EndMinecraftPlusV2.EndMinecraftPlusV2.main(EndMinecraftPlusV2.java:20)`

**Comment by SerendipityR-2022** [comment]
已解决，请更新版本。
